name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  

      - name: Install dependencies
        run: npm install  
        
      - name: Build project
        run: npm run build

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Setup SSH private key
        run: |
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH host key
        run:
          ssh-keyscan -H -p 27015 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Connect and pull
        run: |
          echo "Attempting SSH connection..."
            ssh -o StrictHostKeyChecking=no -p 27015 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            echo "Connected to the remote server."

          # Creo la variable WORK_DIRECTORY que contiene la ruta al directorio teachers  
            WORK_DIRECTORY="/home/${{ secrets.SSH_USER }}/${{ secrets.WORK_DIR }}"

          # Compruebo si existe dicha rura, si no existe la creo  
            if [ ! -d "$WORK_DIRECTORY" ]; then
            mkdir -p "$WORK_DIRECTORY"
            fi
            cd "$WORK_DIRECTORY"

          # Comprueba si el directorio git no existe, si es asi la inicializa y se agrega el remoto 
            if [ ! -d ".git" ]; then
              echo "Initializing a new git repository."
              git init
              git remote add origin ${{ secrets.REPO_ORIGIN }}
            fi

          # Descarga todos los cambios desde el repositorio remoto origin, repositorio principal  
            git fetch origin
            
            git checkout master
            git reset --hard origin/master
            git pull origin master
          EOF

      - name: Clean up
        run: rm -rf ~/.ssh
