name: Deploy to Ifastnet

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
  
      - name: Install dependencies
        run: npm install
  
      - name: Build project
        run: npm run build

      - name: Debug Secrets
        run: echo "FTP_USERNAME is set" && echo "FTP_PASSWORD is set"

      # - name: Setup FTP Deply
      #   uses: SamKirkland/FTP-Deploy-Action@4.1.0
      #   with:
      #     ftp-server: ftp.sangut.site
      #     ftp-username: ${{ secrets.FTP_USERNAME }}
      #     ftp-password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./dist # Ajusta esto al diretorio que contiene los archivos  a desplegar

