on: 
    push:
        branches:
            - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5

    - name: Debug Secrets
      run: echo "FTP_USERNAME is set to ${{ secrets.FTP_USERNAME }}" && echo "FTP_PASSWORD is set"
    #   env:
    #     FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
    #     FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

  