on: 
    push:
        branches:
            - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Debug Secrets
      run: echo "FTP_USERNAME is set to ${{ secrets.FTP_USERNAME }}" && echo "FTP_PASSWORD is set"

    - name: Setup FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: ftp://ftp.sangut.site
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist